name: Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *" # Schedule the workflow to run every 12 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake
        run: |
          # Fetch contribution data from GitHub API
          curl -sS "https://api.github.com/users/amir-ee/repos" | jq '.[] | .name' > repositories.txt
          while IFS= read -r repo; do
            curl -sS "https://api.github.com/repos/amir-ee/$repo/commits" | jq '.[].commit.author.date' | cut -c 1-10 >> github-contribution-snake.txt
          done <repositories.txt
          rm repositories.txt

          # Generate the snake graph
          npx github-contribution-snake --input github-contribution-snake.txt --output github-contribution-snake.svg

      - name: Commit and Push Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md github-contribution-snake.svg
          git commit -m "Update snake eating contributions ðŸ"
          git push
